# Generated by Django 2.1.1 on 2018-10-02 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181001_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 7, 34, 33, 6887, tzinfo=utc)),
        ),
    ]
