# Generated by Django 2.1.1 on 2018-10-02 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181002_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 9, 54, 12, 756505, tzinfo=utc)),
        ),
    ]
