# Generated by Django 2.1.1 on 2018-10-02 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181002_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 11, 35, 47, 932760, tzinfo=utc)),
        ),
    ]
