# Generated by Django 2.1.1 on 2018-10-06 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181007_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 20, 34, 51, 646095, tzinfo=utc)),
        ),
    ]
